services:
  mongo:
    image: mongo:8
    container_name: mongo-dev
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: toppi_business
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: toppilife-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
